# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3af027ed47bfa49c23ee99d395e3b96fd022929b0780d8ba611e63220ed20393692717cea5db18820269d52ea0c29914c95cd465c96758938560e16f1039ad14

test:
  secret_key_base: 002e4827e75a81e34e3c03e9b60481d523089ee3edc224dc2ce5d290778fbb27c81263a17576b29e68ef8dcd87e8dd48188d46ff535be7ea44bcb12cc4e97d68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
